README.md, src/Keboola/S3Extractor/Extractor.php, tests/Keboola/S3ExtractorTest/SubfoldersTest.php, tests/Keboola/S3ExtractorTest/WildcardKeyTest.php
=> feat: store wildcard files in /data/out/files/wildcard

README.md, src/Keboola/S3Extractor/Extractor.php, tests/Keboola/S3ExtractorTest/NewFilesOnlyTest.php, tests/Keboola/S3ExtractorTest/SubfoldersTest.php, tests/Keboola/S3ExtractorTest/WildcardKeyTest.php, tests/_data/collision-file1.csv, tests/_data/collision/file1.csv, tests/_data/folder2/collision-file1.csv, tests/_data/folder2/collision/file1.csv
=> feat: flatten folder structure for subfolders

README.md, src/Keboola/S3Extractor/Application.php, src/Keboola/S3Extractor/ConfigDefinition.php, src/Keboola/S3Extractor/Extractor.php, src/run.php, tests/Keboola/S3ExtractorTest/ApplicationTest.php, tests/Keboola/S3ExtractorTest/ConfigDefinitionTest.php, tests/Keboola/S3ExtractorTest/ExceptionsTest.php, tests/Keboola/S3ExtractorTest/NewFilesOnlyTest.php, tests/Keboola/S3ExtractorTest/OneFileTest.php, tests/Keboola/S3ExtractorTest/SubfoldersTest.php, tests/Keboola/S3ExtractorTest/WildcardKeyTest.php
=> feat: saveAs parameter

.travis.yml, deploy.sh
=> feat: integration job

README.md, src/Keboola/S3Extractor/Extractor.php, tests/Keboola/S3ExtractorTest/Functional/LimitFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/NewFilesOnlyEqualTimestampFunctionalTest.php, tests/loadS3.php
=> feat: add list of files downloaded in the last timestamp second to state

README.md, src/Keboola/S3Extractor/ConfigDefinition.php, src/Keboola/S3Extractor/Extractor.php, tests/Keboola/S3ExtractorTest/Functional/ApplicationFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/ExceptionsFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/NewFilesOnlyFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/OneFileFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/SaveAsFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/SubfoldersFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/WildcardKeyFunctionalTest.php, tests/Keboola/S3ExtractorTest/Unit/ConfigDefinitionTest.php
=> feat: remove 1000 files limit

Dockerfile, composer.json, composer.lock, docker/dockerfile/code-coverage
=> Update PHP 7.2

src/Keboola/S3Extractor/Application.php, tests/Keboola/S3ExtractorTest/Functional/ExceptionsFunctionalTest.php
=> Fix missing wildcard flag or path file

src/Keboola/S3Extractor/Application.php, src/Keboola/S3Extractor/S3ExceptionConverter.php, tests/Keboola/S3ExtractorTest/Unit/S3ExceptionConverterTest.php
Na základě #36 a #28 jsem udělal malý refactoring, který nám pomůže lépe testovat/převádět `S3Exception` na user error.
=> Refactoring exception

composer.json, composer.lock, src/Keboola/S3Extractor/DownloadFile.php, src/Keboola/S3Extractor/Extractor.php, src/Keboola/S3Extractor/S3ExceptionConverter.php, tests/Keboola/S3ExtractorTest/Functional/FunctionalTestCase.php, tests/Keboola/S3ExtractorTest/Functional/RetryDownloadFileTest.php, tests/Keboola/S3ExtractorTest/Unit/S3ExceptionConverterTest.php
This closes #36 and closes #38 
~~FYI před merge/review prosím nejdříve integrovat https://github.com/keboola/aws-s3-extractor/pull/42~~
=> Add retry download file & user exception for slow down

src/Keboola/S3Extractor/Application.php, src/Keboola/S3Extractor/S3ExceptionConverter.php, tests/Keboola/S3ExtractorTest/Functional/ExceptionsFunctionalTest.php, tests/Keboola/S3ExtractorTest/Unit/S3ExceptionConverterTest.php
=> Correction message for key not found

composer.json, composer.lock, phpstan.neon, src/Keboola/S3Extractor/Application.php, src/Keboola/S3Extractor/Config.php, src/Keboola/S3Extractor/ConfigDefinition.php, src/Keboola/S3Extractor/DownloadFile.php, src/Keboola/S3Extractor/Exception.php, src/Keboola/S3Extractor/Extractor.php, src/Keboola/S3Extractor/S3ExceptionConverter.php, src/run.php, tests/Keboola/S3ExtractorTest/Functional/ApplicationFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/ExceptionsFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/FunctionalTestCase.php, tests/Keboola/S3ExtractorTest/Functional/LimitFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/NewFilesOnlyEqualTimestampFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/NewFilesOnlyFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/OneFileFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/SaveAsFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/SubfolderMatchingWildcardKeyFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/SubfoldersFunctionalTest.php, tests/Keboola/S3ExtractorTest/Functional/WildcardKeyFunctionalTest.php, tests/Keboola/S3ExtractorTest/Unit/ConfigDefinitionTest.php, tests/Keboola/S3ExtractorTest/Unit/S3ExceptionConverterTest.php
Resolve #29 
Musel jsem toho plno změnit, CR se bude dělat blbě. Ale když se to vezme jeden commit po druhém, mělo by to být čitelné.
Codeclimate a refactoring na php use strict types udělám po merge v samostatném PR.
=> Upgrade to php-component

src/Keboola/S3Extractor/Application.php, src/Keboola/S3Extractor/ConfigDefinition.php, tests/Keboola/S3ExtractorTest/Unit/ConfigDefinitionTest.php
=> Move wildcard validation to configuration

phpunit.xml.dist
=> Remove phpunit syntax check

composer.json, composer.lock, src/Keboola/S3Extractor/Extractor.php, tests/Functional/ApplicationFunctionalTest.php, tests/Functional/LimitFunctionalTest.php, tests/Functional/NewFilesOnlyEqualTimestampFunctionalTest.php, tests/Functional/NewFilesOnlyFunctionalTest.php, tests/Functional/OneFileFunctionalTest.php, tests/Functional/SaveAsFunctionalTest.php, tests/Functional/SubfolderMatchingWildcardKeyFunctionalTest.php, tests/Functional/SubfoldersFunctionalTest.php, tests/Functional/WildcardKeyFunctionalTest.php
=> Feature log downloaded data size

src/Keboola/S3Extractor/Extractor.php, tests/Functional/ApplicationFunctionalTest.php, tests/Functional/LimitFunctionalTest.php, tests/Functional/NewFilesOnlyEqualTimestampFunctionalTest.php, tests/Functional/NewFilesOnlyFunctionalTest.php, tests/Functional/OneFileFunctionalTest.php, tests/Functional/SaveAsFunctionalTest.php, tests/Functional/SubfolderMatchingWildcardKeyFunctionalTest.php, tests/Functional/SubfoldersFunctionalTest.php, tests/Functional/WildcardKeyFunctionalTest.php
https://keboola.atlassian.net/browse/COM-233
=> COM-233 Add aditional logging

src/Keboola/S3Extractor/Extractor.php
https://keboola.atlassian.net/browse/COM-233
=> COM-233 Correctly increase number of files to download

src/Keboola/S3Extractor/Extractor.php
Solving - https://keboola.atlassian.net/browse/COM-239
=> use ListObjectV2

tests/Functional/FunctionalTestCase.php, tests/bootstrap.php, tests/loadS3.php
Solving - https://keboola.atlassian.net/browse/COM-241
=> Tests are failing randomly

deploy.sh
Solving - https://keboola.atlassian.net/browse/COM-334
=> update deploy script

src/Keboola/S3Extractor/Application.php, src/Keboola/S3Extractor/Extractor.php, src/Keboola/S3Extractor/GetExternalIdDefinition.php, tests/Functional/ApplicationFunctionalTest.php
Solving - https://keboola.atlassian.net/browse/COM-361
=> added async action for getting external-id

src/Keboola/S3Extractor/Extractor.php
Jira - https://keboola.atlassian.net/browse/COM-1362
=> Fix incremental fetching (sort files)

src/Keboola/S3Extractor/Extractor.php, tests/Functional/NewFilesOnlyFunctionalTest.php, tests/Functional/new-files-only/download-from-updated/expected/data/out/files/file2.csv
Jira - https://keboola.atlassian.net/browse/COM-1363
=> Fix downloading new files

README.md, src/Keboola/S3Extractor/Extractor.php, src/Keboola/S3Extractor/S3ExceptionConverter.php
JIRA: https://keboola.atlassian.net/browse/CM-353
Nevím jak jednoduše zreplikovat, takže je to bez testu, není k tomu ani pořádný stack trace :-/
=> Add retries

.github/workflows/push.yml, src/Keboola/S3Extractor/Extractor.php
Jira - https://keboola.atlassian.net/browse/CM-460
=> Paginator for listObjectV2 method

Dockerfile, composer.json, composer.lock, src/Keboola/S3Extractor/Config.php, src/Keboola/S3Extractor/Extractor.php, src/Keboola/S3Extractor/File.php, src/Keboola/S3Extractor/Finder.php, src/Keboola/S3Extractor/FinderResult.php, src/Keboola/S3Extractor/S3AsyncDownloader.php, src/Keboola/S3Extractor/State.php, tests/Functional/ExceptionsFunctionalTest.php, tests/Functional/RetryDownloadFileTest.php
Jira: https://keboola.atlassian.net/browse/CM-307
Slack: https://keboola.slack.com/archives/CQ1ASK06M/p1680534704511499?thread_ts=1680534064.112469&cid=CQ1ASK06M
--------------------
Keď sa to nasadí a skontroluje, tak by sme mali vedieť presne, koľko pamate komponenta potrebuje.
**Asi bude stačiť `512MB`. Toto je prelistovanie a stiahnutie `2.3M` :exclamation: súborov, jeden mal `~0.5MB`.**
_Note_: 
- Je potrebné pozerať graf **`container.memory.rss`**.
- Pretože `container.memory.usage` obsahuje aj cache a unused pages (teda pamat, ktorá sa v prípade potreby uvoľní). 
- A tá vyzerá takto (3GB, rovná čiara):
- Ale to nie je relevatné, ak by bol limit 2GB, tak to budu 2GB.
- Dolezite je, ze job dobehol a nebol ziaden OOM Kill.
--------------
Job ma 3 fázy, najviac `memory` berie samotný …
=> Memory usage optimalization
